const assert = require("node:assert/strict");
const { test, after } = require("node:test");
const admin = require("../drive/node_modules/firebase-admin");
const { createLevelHandler } = require("../drive/activeClassroomLevels");
const { createUnitHandlers } = require("../drive/activeClassroomUnit");
const { createDesktopHandlers } = require("../drive/activeClassroomDesktop");
const { createPublicationJobs } = require("../drive/activeClassroomPublicationJobs");
if (!process.env.FIRESTORE_EMULATOR_HOST) throw new Error("Requiere emulador Firestore.");
const app = admin.initializeApp({ projectId: "security-rules-audit" }, "admin-flow-tests");
const db = app.firestore();
const getProfile = async uid => ({ active: true, role: uid === "admin" ? "admin" : "requester" });
const timestamp = () => admin.firestore.FieldValue.serverTimestamp();
const request = data => ({ auth: { uid: "admin" }, data });
const files = new Map();
let networkError = false;
const resolveFile = async (_profile, id) => {
  if (networkError) throw Object.assign(new Error("network"), { code: "unavailable" });
  if (!files.has(id)) throw Object.assign(new Error("gone"), { code: "not-found" });
  return files.get(id);
};
const units = createUnitHandlers({ db, getProfile, timestamp, resolveFile, prepareResource: async () => ({ path: `active-classroom/publications/files/${"a".repeat(64)}`, generation: "1", mimeType: "application/pdf", name: "Presentación.pdf", sizeBytes: 20, checksums: { sha256: "a".repeat(64) } }) });
const manage = createLevelHandler({ db, getProfile, timestamp });
const unitId = "admin-flow-unit";
const created = [];
after(async () => {
  await db.recursiveDelete(db.doc(`activeClassroomUnits/${unitId}`));
  await db.doc(`activeClassroomFolders/${unitId}`).delete();
  for (const id of created) await db.doc(`activeClassroomFolders/${id}`).delete();
  for (const id of ["admin-main", "admin-audio", "admin-replacement"]) await db.doc(`activeClassroomResources/${id}`).delete();
  await app.delete();
});
test("administración real: niveles, refresco múltiple, reemplazo/quitar e inmutabilidad", async () => {
  const first = await manage(request({ action: "create", name: "Inglés avanzado", position: 0 })); created.push(first.id);
  const second = await manage(request({ action: "create", name: "Conversación", position: 1 })); created.push(second.id);
  await manage(request({ action: "update", levelId: first.id, name: "Adultos C1" }));
  assert.equal((await db.doc(`activeClassroomFolders/${first.id}`).get()).data().name, "Adultos C1");
  const desktop = createDesktopHandlers({ db, getProfile, resolveFile });
  const list = await desktop.list(request({}));
  assert.equal(list.levels.find(level => level.id === first.id).name, "Adultos C1");
  assert.ok(list.levels.some(level => level.id === second.id));
  const all = (await db.collection("activeClassroomFolders").where("kind", "==", "level").get()).docs.map(doc => doc.id);
  await manage(request({ action: "reorder", levelIds: all.reverse() }));
  assert.deepEqual((await desktop.list(request({}))).levels.map(level => level.id), all);
  await db.doc(`activeClassroomFolders/${unitId}`).set({ name: "Unit", parentId: first.id, kind: "unit", active: true });
  await assert.rejects(manage(request({ action: "delete", levelId: first.id })), { code: "failed-precondition" });
  for (const id of ["admin-main", "admin-audio", "admin-replacement"]) {
    const file = { id, name: `${id}.pdf`, mimeType: "application/pdf", version: "1", modifiedTime: "2026-10-01", md5Checksum: "old" };
    files.set(id, file);
    await db.doc(`activeClassroomResources/${id}`).set({ folderId: unitId, source: "drive", driveFileId: id, sourceName: file.name, name: file.name, mimeType: file.mimeType, kind: "document", driveVersion: "1", driveModifiedTime: file.modifiedTime, driveMd5Checksum: "old", archived: false });
  }
  let draft = { name: "Unit", levelId: first.id, status: "active", metadata: { code: "LEGACY", language: "es", tags: ["preservada"] }, mainPresentationId: "admin-main", generalResourceIds: ["admin-audio"], slides: [{ slideId: "admin-slide", resourceIds: [], metadata: { pageNumber: 1 } }] };
  let saved = await units.save(request({ unitId, draft, expectedRevision: 0 }));
  assert.equal((await units.validatePublication(request({ unitId, expectedRevision: saved.draftRevision }))).ready, true);
  await units.publish(request({ unitId, expectedRevision: saved.draftRevision }));
  const publication = db.doc(`activeClassroomUnits/${unitId}/publications/1`);
  const frozen = JSON.stringify((await publication.get()).data());
  for (const id of ["admin-main", "admin-audio"]) files.set(id, { ...files.get(id), version: "2", md5Checksum: "new", modifiedTime: "2026-10-09" });
  const validation = await units.validatePublication(request({ unitId, expectedRevision: saved.draftRevision }));
  assert.equal(validation.ready, false); assert.equal(validation.canPublishCurrent, false);
  assert.equal(validation.results.filter(entry => entry.status === "changed").length, 2);
  const jobs = createPublicationJobs({ db, units, getProfile, enqueue: async () => { throw new Error("must not enqueue"); } });
  await assert.rejects(jobs.start(request({ unitId, expectedRevision: saved.draftRevision })), /Hay 2 archivos/);
  assert.equal((await db.doc(`activeClassroomUnits/${unitId}`).get()).data().publishedVersion, 1);
  for (const id of ["admin-main", "admin-audio"]) {
    const result = await units.refreshDrive(request({ unitId, resourceId: id, expectedRevision: saved.draftRevision }));
    saved.draftRevision = result.draftRevision;
    assert.equal(result.resource.driveVersion, "2"); assert.equal(result.resource.driveMd5Checksum, "new");
  }
  assert.equal((await units.validatePublication(request({ unitId, expectedRevision: saved.draftRevision }))).ready, true);
  const repeated = await units.refreshDrive(request({ unitId, resourceId: "admin-main", expectedRevision: saved.draftRevision }));
  assert.equal(repeated.unchanged, true); assert.equal(repeated.draftRevision, saved.draftRevision);
  files.delete("admin-main");
  assert.equal((await units.checkDrive(request({ unitId, resourceIds: ["admin-main"] }))).results[0].status, "unavailable");
  networkError = true;
  assert.equal((await units.checkDrive(request({ unitId, resourceIds: ["admin-audio"] }))).results[0].status, "error"); networkError = false;
  const { replaceDraftResource } = await import("../src/active-classroom/utils/draftResources.js");
  draft = replaceDraftResource(saved.draft, "admin-main");
  saved = await units.save(request({ unitId, draft, expectedRevision: saved.draftRevision }));
  assert.equal(saved.draft.mainPresentationId, null); assert.deepEqual(saved.draft.slides, []);
  draft = { ...replaceDraftResource(saved.draft, null, "admin-replacement", true), slides: [{ slideId: "new-slide", resourceIds: [], metadata: { pageNumber: 1 } }] };
  saved = await units.save(request({ unitId, draft, expectedRevision: saved.draftRevision }));
  assert.equal(saved.draft.mainPresentationId, "admin-replacement");
  assert.equal(saved.draft.metadata.code, "LEGACY");
  assert.equal(JSON.stringify((await publication.get()).data()), frozen);
  await manage(request({ action: "update", levelId: first.id, active: false }));
  await assert.rejects(units.preparePublish(request({ unitId, expectedRevision: saved.draftRevision })), { code: "failed-precondition" });
  await units.save(request({ unitId, draft: { ...saved.draft, levelId: second.id }, expectedRevision: saved.draftRevision }));
  await manage(request({ action: "delete", levelId: first.id }));
  assert.equal((await db.doc(`activeClassroomFolders/${unitId}`).get()).data().parentId, second.id);
  assert.equal(JSON.stringify((await publication.get()).data()), frozen);
  await assert.rejects(manage({ auth: { uid: "reader" }, data: { action: "create", name: "Blocked" } }), { code: "permission-denied" });
});
