import { useState } from "react";

export default function EditorialAcademicElementInspector({ element, actions, onRegenerate }) {
  const [accepted, setAccepted] = useState(() => (element?.answerData?.acceptedValues || []).join("\n"));
  if (!element) return null;
  const update = (changes) => actions.updateElement(element.id, changes);
  const updateAnswer = (changes) => update({ answerData: { type: element.answerData?.type || element.exerciseData?.type || "custom", value: element.answerData?.value ?? "", acceptedValues: element.answerData?.acceptedValues || [], explanation: element.answerData?.explanation || "", ...changes } });
  const booleanAnswer = element.answerData?.type === "true_false";
  const updateVisibility = (visibilityMode) => element.academicGroupId
    ? actions.updateAcademicGroup(element.academicGroupId, { visibilityMode })
    : update({ visibilityMode });
  return <section className="editorial-academic-inspector"><header><strong>Académico</strong><span>{element.academicBlockType || element.exerciseData?.type || "Elemento"}</span></header><label className="editorial-inspector-field wide"><span>{element.academicGroupId ? "Visibilidad del grupo" : "Visibilidad de variante"}</span><select value={element.visibilityMode || "both"} onChange={(event) => updateVisibility(event.target.value)}><option value="both">Alumno y maestro</option><option value="student">Solo alumno</option><option value="teacher">Solo maestro</option></select></label>{element.studentContent !== undefined && <><label className="editorial-inspector-field wide"><span>Texto Alumno</span><textarea rows="4" value={element.studentContent} onChange={(event) => update({ studentContent: event.target.value, content: event.target.value })} /></label><label className="editorial-inspector-field wide"><span>Texto Maestro</span><textarea rows="4" value={element.teacherContent || ""} onChange={(event) => update({ teacherContent: event.target.value })} /></label></>}{element.answerData && <>{booleanAnswer ? <label className="editorial-inspector-field wide"><span>Respuesta correcta</span><select value={element.answerData.value === true ? "true" : element.answerData.value === false ? "false" : ""} onChange={(event) => updateAnswer({ value: event.target.value === "" ? null : event.target.value === "true" })}><option value="">Sin configurar</option><option value="true">Verdadero</option><option value="false">Falso</option></select></label> : <label className="editorial-inspector-field wide"><span>Respuesta correcta</span><textarea rows="2" value={Array.isArray(element.answerData.value) ? element.answerData.value.join("\n") : String(element.answerData.value ?? "")} onChange={(event) => updateAnswer({ value: Array.isArray(element.answerData.value) ? event.target.value.split(/\r?\n/).filter(Boolean) : event.target.value })} /></label>}<label className="editorial-inspector-field wide"><span>Respuestas aceptadas · una por línea</span><textarea rows="3" value={accepted} onChange={(event) => setAccepted(event.target.value)} onBlur={() => updateAnswer({ acceptedValues: accepted.split(/\r?\n/).map((item) => item.trim()).filter(Boolean) })} /></label><label className="editorial-inspector-field wide"><span>Explicación</span><textarea rows="3" value={element.answerData.explanation || ""} onChange={(event) => updateAnswer({ explanation: event.target.value })} /></label></>}{element.exerciseData && onRegenerate && <button type="button" className="editorial-button compact secondary" onClick={() => onRegenerate(element)}>Regenerar diseño</button>}</section>;
}
