import { useState } from "react";

const TYPES = [["cover", "Portadas"], ["front_matter", "Preliminares"], ["index", "Secciones de índice"], ["unit", "Unidades"], ["chapter", "Capítulos"], ["resources", "Recursos"], ["back_cover", "Contraportadas"], ["custom", "Secciones personalizadas"]];

export default function EditorialIndexDialog({ open, initialConfig, sections = [], onClose, onSubmit }) {
  const [values, setValues] = useState(() => ({ sectionTypes: ["unit", "chapter", "resources"], includeLessons: true, indent: "    ", leader: ".", lineWidth: 58, ...(initialConfig || {}) }));
  if (!open) return null;
  function toggle(type) { setValues((current) => ({ ...current, sectionTypes: current.sectionTypes.includes(type) ? current.sectionTypes.filter((item) => item !== type) : [...current.sectionTypes, type] })); }
  function toggleSection(sectionId) { setValues((current) => ({ ...current, excludedSectionIds: current.excludedSectionIds?.includes(sectionId) ? current.excludedSectionIds.filter((id) => id !== sectionId) : [...(current.excludedSectionIds || []), sectionId] })); }
  return <div className="editorial-dialog-layer" role="presentation"><button type="button" className="editorial-dialog-backdrop" aria-label="Cerrar ventana" onClick={onClose} /><section className="editorial-dialog editorial-production-dialog" role="dialog" aria-modal="true" aria-label="Configurar índice automático"><header><div><span>Índice vinculado</span><h2>Configurar índice</h2></div><button type="button" onClick={onClose}>Cerrar</button></header><div className="editorial-production-form"><fieldset><legend>Tipos</legend>{TYPES.map(([value, label]) => <label className="check-row" key={value}><input type="checkbox" checked={values.sectionTypes.includes(value)} onChange={() => toggle(value)} />{label}</label>)}<label className="check-row"><input type="checkbox" checked={values.includeLessons} onChange={(event) => setValues({ ...values, includeLessons: event.target.checked })} />Lecciones vinculadas</label></fieldset><fieldset><legend>Secciones elegidas</legend>{sections.map((section) => <label className="check-row" key={section.id}><input type="checkbox" checked={!values.excludedSectionIds?.includes(section.id)} onChange={() => toggleSection(section.id)} />{section.name}</label>)}</fieldset><label>Puntos guía<select value={values.leader} onChange={(event) => setValues({ ...values, leader: event.target.value })}><option value=".">Puntos</option><option value="·">Punto medio</option><option value="none">Sin guía</option></select></label><label>Ancho de línea<input type="number" min="20" max="100" value={values.lineWidth} onChange={(event) => setValues({ ...values, lineWidth: Number(event.target.value) })} /></label><label>Sangría<input value={values.indent} onChange={(event) => setValues({ ...values, indent: event.target.value })} /></label></div><footer><button type="button" onClick={onClose}>Cancelar</button><button type="button" className="editorial-button primary" onClick={() => onSubmit(values)} disabled={!values.sectionTypes.length}>Aplicar</button></footer></section></div>;
}
