import { icon } from "./icons.ts";
const shortcut = (keys: string[], label: string) => `<span>${keys.map(key => `<kbd>${key}</kbd>`).join("")}<small>${label}</small></span>`;
export function playerMarkup(): string {
  return `<main class="classroom-player"><header class="player-header"><div><p class="section-kicker">ACTIVE CLASSROOM · <span data-local>SOLO ARCHIVOS LOCALES</span></p><h1 data-unit></h1><small data-version></small></div><button class="button button-outline" data-exit>${icon("previous")}Volver a Biblioteca</button></header>
    <div class="player-layout"><section class="player-main"><header class="player-content-title" data-view-title><div><h2 data-resource-name></h2><p data-position></p></div><button class="button button-outline" data-presentation>${icon("previous")}Volver a presentación</button></header>
      <div class="player-stage"><div data-renderer class="player-renderer"></div><p data-status role="status" class="player-status"></p><button class="player-stage-fullscreen" data-command="FULLSCREEN" aria-label="Pantalla completa">${icon("fullscreen")}</button><button class="player-stage-arrow is-previous" data-stage-previous aria-label="Diapositiva anterior">${icon("previous")}</button><button class="player-stage-arrow is-next" data-stage-next aria-label="Diapositiva siguiente">${icon("next")}</button><span class="player-stage-counter" data-stage-counter></span><span class="player-build-indicator" data-build hidden></span></div>
      <section class="player-controls" aria-label="Controles de clase"><div class="player-slide-controls"><button class="button button-outline" data-slide-previous>${icon("previous")}Anterior</button><span class="slide-progress-wrap"><progress data-slide-progress max="1" value="0" aria-label="Progreso de la clase"></progress><i data-progress-thumb></i></span><span class="player-page-indicator" data-counter></span><button class="button button-outline" data-slide-next>Siguiente${icon("next")}</button><button class="button button-outline" data-command="FULLSCREEN">${icon("fullscreen")}Pantalla completa</button></div>
      <div data-media class="player-media-controls"><div class="ui-cluster"><button class="button button-primary" data-command="PLAY_PAUSE">${icon("play")}Reproducir</button><button class="button button-outline" data-command="STOP">${icon("stop")}Detener</button><button class="button button-outline" data-command="SEEK_BACKWARD">−10 s</button><button class="button button-outline" data-command="SEEK_FORWARD">+10 s</button><span data-time>0:00 / 0:00</span></div><label class="player-range">Reproducción<input data-seek aria-label="Posición de reproducción" type="range" min="0" max="0" step="0.1" value="0" /></label><div class="ui-cluster"><label class="player-range">${icon("volume")}Volumen<input data-volume aria-label="Volumen" type="range" min="0" max="1" step="0.05" value="0.8" /></label><button class="button button-outline" data-command="MUTE" aria-pressed="false">${icon("mute")}Silenciar</button></div></div></section>
      <div class="player-shortcuts" aria-label="Atajos de teclado"><strong>Atajos de teclado:</strong>${shortcut(["←"], "Anterior")}${shortcut(["→"], "Siguiente")}${shortcut(["Espacio"], "Reproducir")}${shortcut(["J", "L"], "±10 s")}${shortcut(["↑", "↓"], "Volumen")}${shortcut(["M"], "Silencio")}${shortcut(["F"], "Pantalla completa")}${shortcut(["Esc"], "Volver")}</div></section>
    <aside class="player-resources"><section class="ui-card player-projection"><header class="player-panel-heading"><h2>${icon("projector")}Proyector</h2><span class="projector-connection" data-projector-connected></span></header><label>Pantalla<select data-monitor aria-label="Monitor del proyector"></select></label><button class="button button-primary" data-project>${icon("projector")}Proyectar</button><p data-projector-status role="status"></p><details class="player-notes"><summary>Notas de la diapositiva</summary><small>Audio exclusivo de esta ventana. Vista principal como preview.</small><p data-notes></p></details></section>
    <div class="player-resource-sections"><section class="ui-card player-slides-card"><header class="player-panel-heading"><h2>${icon("slides")}Diapositivas</h2><span data-slide-count></span></header><nav data-slides class="player-scroll-list" aria-label="Diapositivas" tabindex="0"></nav></section><section class="ui-card"><header class="player-panel-heading"><h2>${icon("resource")}Recursos de la diapositiva</h2><span data-associated-count></span></header><div data-associated class="player-scroll-list" aria-label="Recursos de la diapositiva" tabindex="0"></div></section><section class="ui-card"><header class="player-panel-heading"><h2>${icon("folder")}Recursos generales</h2><span data-general-count></span></header><div data-general class="player-scroll-list" aria-label="Recursos generales" tabindex="0"></div></section></div></aside></div></main>`;
}
